Local setup taking precedence over Docker
techops-recsys-lateral-hiring/dataengineer-transformations-python pull request #36
Opened 2023-06-09 12:32 UTC by jmolina4

We have seen that running the integration tests in docker takes a long time impacting the experience when doing TDD in the interview. We want to change that so that Local setup is the preferred way to go.

2023-06-12 13:23 UTC, lleites approved these changes

2023-06-13 13:10 UTC, daialv approved these changes

2023-06-13 21:31 UTC, daialv requested changes

2023-06-13 21:31 UTC, daialv commented on README-DOCKER.md
> + - For distance calculation, consider using [**Harvesine formula**](https://en.wikipedia.org/wiki/Haversine_formula) as an option.
This typo has been bugging me for so long (almost 2 years). @jmolina4 can you please change Ha_r_vesine into Have_r_sine? Thanks!

2023-06-13 21:31 UTC, daialv commented on README-DOCKER.md
> + - For distance calculation, consider using [**Harvesine formula**](https://en.wikipedia.org/wiki/Haversine_formula) as an option.
Could you please take a look at README.md on this as well?

2023-06-14 10:52 UTC, svishal9 requested changes
1. I'm not convinced with this change because it does not resolve the underlying problem.
2. moving back to make file pattern will surface all those issues because of which we moved to "go" file pattern. it will also complicate as way of execution will change across platforms.
3. have we tested the instructions on Windows?

2023-06-14 10:52 UTC, svishal9 commented on README.md
> -| 6      | ./go.sh run-local-unit-test       | Run unit tests on local machine   |
What are we trying to achieve by moving back to make file syntax? AFAIR we moved to single "go" file to ensure uniformity across different platforms (Mac, Linux, Win, Container).
How moving to make file resolve performance issue?

2023-06-14 10:52 UTC, svishal9 commented on README.md
> -We use [`batect`](https://batect.dev/) to dockerise the tasks in this exercise.
What is the issue with container which impacts performance? Is download of image taking time? is container runtime causing issue? is the issue with spark driver? what if we encounter this issue in local as well?
I feel we should investigate.

2023-06-14 13:22 UTC, jmolina4 commented on README.md
> -We use [`batect`](https://batect.dev/) to dockerise the tasks in this exercise.
The issue is when running integration tests.

We discussed that and yes, we need to investigate a way to use docker efficiently, but in the meantime with need to have a setup where we can do tdd to assess the candidate skills.

2023-06-15 00:09 UTC, svishal9 commented on README.md
> -| 6      | ./go.sh run-local-unit-test       | Run unit tests on local machine   |
Thanks for the response @jmolina4 !
this comment was more about changing the patter back to makefile. How is it going to help?
All our repos (python/java/scala) use "go" file pattern.

2023-06-15 00:12 UTC, svishal9 commented on README.md
> -We use [`batect`](https://batect.dev/) to dockerise the tasks in this exercise.
Hi @jmolina4 ,

Following is the result from my machine:

![image](https://github.com/techops-recsys-lateral-hiring/dataengineer-transformations-python/assets/61403678/2c3964ea-28d9-4f34-8e89-8285b5b63b0f)

I'm not able to simulate the issue. Hence the suggestion of finding the root cause.

On a different note, even if the issue exists, this change is not going to fix it. So if someone has to use container, they would not be able to get better experience.

2023-06-15 00:13 UTC, svishal9 commented
> 1. I'm not convinced with this change because it does not resolve the underlying problem.
> 2. moving back to make file pattern will surface all those issues because of which we moved to "go" file pattern. it will also complicate as way of execution will change across platforms.
> 3. have we tested the instructions on Windows?

any comments on Windows testing @jmolina4 ?

2023-06-15 07:02 UTC, jmolina4 commented on README.md
> -| 6      | ./go.sh run-local-unit-test       | Run unit tests on local machine   |
I don't think this is a final solution, but instead a temporary one. The idea would be to go back to container approach if we find a way to speed it up.

Honestly I just changed the order of the READMEs, so I didn't do any change to the content to the existing readmes.

2023-06-15 07:03 UTC, jmolina4 commented
> any comments on Windows testing @jmolina4 ?

I saw @daialv will give it a try in a windows machine.

2023-06-15 07:58 UTC, jmolina4 commented on README.md
> -| 6      | ./go.sh run-local-unit-test       | Run unit tests on local machine   |
I just replaced the the make references to use go.sh or go.ps

2023-12-05 08:26 UTC, closed without merging